/*	Heather Sweeny Designs HSD Database - Drop Tables    */

DROP TABLE LINE_ITEM;
DROP TABLE INVOICE;
DROP TABLE PRODUCT;
DROP TABLE SEMINAR_CUSTOMER;
DROP TABLE SEMINAR;
DROP TABLE CUSTOMER;
DROP SEQUENCE seqCID;
DROP SEQUENCE seqSID;
DROP SEQUENCE seqIID;