-- Drop Table
DROP TABLE CONTRACTOR;
DROP TABLE SUPPLIER_LINE_ITEM;
DROP TABLE SUPPLIER;
DROP TABLE LINE_ITEM;
DROP TABLE TIME_CARD;
DROP TABLE PROJECT;
DROP TABLE SKILL;
DROP TABLE EMPLOYEE;
DROP TABLE TOOL;
DROP TABLE VEHICLE;

-- Drop Sequence ID
DROP SEQUENCE SEQCN;
DROP SEQUENCE SEQEID;
DROP SEQUENCE SEQLID;
DROP SEQUENCE SEQPID;
DROP SEQUENCE SEQSID;
DROP SEQUENCE SEQSKID;
DROP SEQUENCE SEQTID;
DROP SEQUENCE SEQVID;
DROP SEQUENCE seqTCID;

-- Drop View
DROP VIEW DETAIL_WORK_HOUR;
DROP VIEW DETAIL_WORK_HOUR_BREAK_DOWN;
DROP VIEW DETAIL_WORK_HOUR_MAR10;
DROP VIEW MINORITIES;
DROP VIEW MINORITY_FEMALE_HOURS;
DROP VIEW MINORITY_MALE_HOURS;
DROP VIEW NON_MINORITIES;
DROP VIEW NON_MINORITY_FEMALE_HOURS;
DROP VIEW NON_MINORITY_MALE_HOURS;