
-- Insert Data for EXHIBIT C - Part C -Detailed Pay Scale Breakdown for Regular Hours (Overtime =1.5 X the Basic Rate)
INSERT INTO PRIMARYKEY.SKILL (SKILLID, SKILLCODE, SKILLCLASSIFICATION, BASICHOURLYRATE, FRINGE) VALUES (seqSKID.nextval, 'LAB', 'Labor', 15, 3);
INSERT INTO PRIMARYKEY.SKILL (SKILLID, SKILLCODE, SKILLCLASSIFICATION, BASICHOURLYRATE, FRINGE) VALUES (seqSKID.nextval, 'MAS', 'Masonry', 17, 3);
INSERT INTO PRIMARYKEY.SKILL (SKILLID, SKILLCODE, SKILLCLASSIFICATION, BASICHOURLYRATE, FRINGE) VALUES (seqSKID.nextval, 'EQP', 'Equipment Operation', 20, 3);

-- Insert EXHIBIT E- LILY LANDSCAPING GENERAL EMPLOYEE INFORMATION FORM
INSERT INTO PRIMARYKEY.EMPLOYEE (EMPLOYEEID, SSN, LASTNAME, FIRSTNAME, MI, STREET, CITY, STATE, ZIP, PHONE, GENDER, MARITALSTATUS, DOB, EEOTYPE) VALUES (1, '390054489
', 'Worker', 'James', 'E ', '1253 Chopping Block Lane', '23', 'IL', '62270     ', '3125554897  ', 'male ', 'Single', TO_DATE('2019-11-10 20:12:17', 'YYYY-MM-DD HH24:MI:SS'), 2);

