
-- Insert Data for EXHIBIT C - Part C -Detailed Pay Scale Breakdown for Regular Hours (Overtime =1.5 X the Basic Rate)
INSERT INTO PRIMARYKEY.SKILL (SKILLID, SKILLCODE, SKILLCLASSIFICATION, BASICHOURLYRATE, FRINGE) VALUES (1, 'LAB', 'Labor', 15, 3);
INSERT INTO PRIMARYKEY.SKILL (SKILLID, SKILLCODE, SKILLCLASSIFICATION, BASICHOURLYRATE, FRINGE) VALUES (2, 'MAS', 'Masonry', 17, 3);
INSERT INTO PRIMARYKEY.SKILL (SKILLID, SKILLCODE, SKILLCLASSIFICATION, BASICHOURLYRATE, FRINGE) VALUES (3, 'EQP', 'Equipment Operation', 20, 3);